#!/bin/bash
VERSION=$1

tar -xJvf bsnes_v$VERSION-source.tar.xz
rm bsnes_v$VERSION-source/bsnes/profile/Super\ Game\ Boy.sfc/boot.rom
rm bsnes_v$VERSION-source/bsnes/profile/Game\ Boy\ Color.sys/boot.rom
rm bsnes_v$VERSION-source/bsnes/profile/Game\ Boy.sys/boot.rom
rm bsnes_v$VERSION-source/bsnes/profile/Super\ Famicom.sys/spc700.rom

tar -cJvf bsnes_v$VERSION-source-noroms.tar.xz bsnes_v$VERSION-source